import { useEffect, useMemo, useRef, useState } from 'react';
import { dbTables } from '../../api/api';
import type {
  CameraSamples,
  GenerateImageRequest,
  GetListRequest,
  ImageGenerationSettings,
  ImageRecord,
  CutRecord,
} from '../../api/type';
import { readSessionImageSettings } from '../../lib/cut-image';
import {
  Button,
  Panel,
  PanelHeader,
  SectionBody,
} from '../ui';
import { CameraSampleChips } from './CameraSampleChips';
import { ImageDetailModal } from './ImageDetailModal';
import { ImageManagerToolbar } from './ImageManagerToolbar';
import { ImageQuickGenerateModal } from './ImageQuickGenerateModal';
import { ImageTileGrid } from './ImageTileGrid';
import {
  DEFAULT_IMAGE_SORT_VALUE,
  FAMILY_SORT,
  IMAGE_MANAGER_PAGE_SIZE,
  IMAGE_SORT_OPTIONS,
  type ImageSortValue,
} from './constants';

const AUTO_PROMPT_CUT_FIELDS = [
  'prompt_situation',
  'prompt_hero',
  'prompt_camera',
  'prompt_detail',
] as const;

const AUTO_PROMPT_CUT_LIST_REQUEST: GetListRequest = {
  offset: 0,
  limit: null,
  selected_ids: [],
  search_text: null,
  text_filter: {},
  filter: {},
  sort: ['id', 'desc'],
};

function getErrorMessage(error: unknown) {
  if (error instanceof Error) {
    return error.message;
  }
  return '요청에 실패했습니다.';
}

function parsePromptTerms(value: string) {
  return value
    .split(',')
    .map((term) => term.trim())
    .filter((term) => term.length > 0);
}

function getImageId(image: ImageRecord) {
  return typeof image.id === 'number' ? image.id : null;
}

function getSortRequest(sortValue: ImageSortValue): GetListRequest['sort'] {
  return (
    IMAGE_SORT_OPTIONS.find((option) => option.value === sortValue)?.sort ??
    IMAGE_SORT_OPTIONS[0].sort
  );
}

function buildListRequest(
  page: number,
  sortValue: ImageSortValue,
  isFamilyMode: boolean,
  searchTerms: string[],
): GetListRequest {
  return {
    offset: (page - 1) * IMAGE_MANAGER_PAGE_SIZE,
    limit: IMAGE_MANAGER_PAGE_SIZE,
    selected_ids: [],
    search_text: null,
    text_filter: searchTerms.length > 0 ? { positive_prompt: searchTerms } : {},
    filter: {},
    sort: isFamilyMode ? FAMILY_SORT : getSortRequest(sortValue),
  };
}

function selectedCutCount(images: ImageRecord[], selectedIds: Set<number>) {
  return images.reduce((total, image) => {
    const imageId = getImageId(image);
    if (imageId === null || !selectedIds.has(imageId)) {
      return total;
    }
    return total + (image.cut_count ?? 0);
  }, 0);
}

function getRandomItem<T>(items: T[]) {
  return items[Math.floor(Math.random() * items.length)] ?? null;
}

function getCameraSamplePool(cameraSamples: CameraSamples) {
  return Object.values(cameraSamples)
    .flatMap((samplesByTag) => Object.keys(samplesByTag))
    .map((sample) => sample.trim())
    .filter((sample) => sample.length > 0);
}

function formatWeightedPromptKeyword(keyword: string, weight: number) {
  if (weight === 1) {
    return keyword;
  }
  return `(${keyword}:${weight.toFixed(1)})`;
}

function buildAutoGeneratePrompt(settings: ImageGenerationSettings, cuts: CutRecord[]) {
  const rawCameraSample = getRandomItem(getCameraSamplePool(settings.camera_samples)) ?? '';
  const cameraSample = rawCameraSample
    ? formatWeightedPromptKeyword(rawCameraSample, 2.0)
    : '';
  const cutPromptParts = AUTO_PROMPT_CUT_FIELDS.map((fieldName) => {
    const cut = getRandomItem(cuts);
    return (cut?.[fieldName] ?? '').trim();
  });
  const positivePrompt = [
    cameraSample,
    ...cutPromptParts,
    settings.prompt_default_positive,
  ]
    .map((part) => part.trim())
    .filter((part) => part.length > 0)
    .join(', ');

  return {
    positivePrompt,
    negativePrompt: settings.prompt_default_negative.trim(),
  };
}

export function ImageManager() {
  const [images, setImages] = useState<ImageRecord[]>([]);
  const [cameraSamples, setCameraSamples] = useState<CameraSamples>({});
  const [searchText, setSearchText] = useState('');
  const [searchTerms, setSearchTerms] = useState<string[]>([]);
  const [sortValue, setSortValue] = useState<ImageSortValue>(DEFAULT_IMAGE_SORT_VALUE);
  const [isFamilyMode, setIsFamilyMode] = useState(false);
  const [isSelectionMode, setIsSelectionMode] = useState(false);
  const [selectedIds, setSelectedIds] = useState<Set<number>>(() => new Set());
  const [lastSelectedImageId, setLastSelectedImageId] = useState<number | null>(null);
  const [detailImage, setDetailImage] = useState<ImageRecord | null>(null);
  const [page, setPage] = useState(1);
  const [totalRows, setTotalRows] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [isDeleting, setIsDeleting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [reloadKey, setReloadKey] = useState(0);
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  const [isAutoGenerationStopping, setIsAutoGenerationStopping] = useState(false);
  const [autoGeneratedCount, setAutoGeneratedCount] = useState(0);
  const [autoGenerationMessage, setAutoGenerationMessage] = useState<string | null>(null);
  const [isQuickGenerateOpen, setIsQuickGenerateOpen] = useState(false);
  const [quickGenerateSettings, setQuickGenerateSettings] = useState<ImageGenerationSettings | null>(null);
  const [quickGeneratePositivePrompt, setQuickGeneratePositivePrompt] = useState('');
  const [quickGenerateNegativePrompt, setQuickGenerateNegativePrompt] = useState('');
  const [isQuickGenerateLoading, setIsQuickGenerateLoading] = useState(false);
  const [isQuickGenerateSubmitting, setIsQuickGenerateSubmitting] = useState(false);
  const [quickGenerateError, setQuickGenerateError] = useState<string | null>(null);
  const autoGenerationStopRef = useRef(false);
  const autoGenerationActiveRef = useRef(false);
  const autoGenerationRunIdRef = useRef(0);
  const isMountedRef = useRef(true);

  const totalPages = useMemo(
    () => Math.max(1, Math.ceil(totalRows / IMAGE_MANAGER_PAGE_SIZE)),
    [totalRows],
  );
  const currentSelectedCutCount = useMemo(
    () => selectedCutCount(images, selectedIds),
    [images, selectedIds],
  );

  useEffect(() => {
    return () => {
      isMountedRef.current = false;
      autoGenerationStopRef.current = true;
      autoGenerationActiveRef.current = false;
      autoGenerationRunIdRef.current += 1;
    };
  }, []);

  useEffect(() => {
    let isActive = true;

    async function loadImages() {
      setIsLoading(true);
      setError(null);
      try {
        const response = await dbTables.Image.listRows(
          buildListRequest(page, sortValue, isFamilyMode, searchTerms),
        );
        if (!isActive) {
          return;
        }
        setImages(response.items);
        setTotalRows(response.total);
      } catch (loadError) {
        if (!isActive) {
          return;
        }
        setImages([]);
        setTotalRows(0);
        setError(getErrorMessage(loadError));
      } finally {
        if (isActive) {
          setIsLoading(false);
        }
      }
    }

    void loadImages();
    return () => {
      isActive = false;
    };
  }, [isFamilyMode, page, reloadKey, searchTerms, sortValue]);

  useEffect(() => {
    let isActive = true;

    async function loadCameraSamples() {
      try {
        const defaults = await dbTables.ImageUtil.getImageSettingsDefaults();
        if (isActive) {
          setCameraSamples(defaults.camera_samples ?? {});
        }
      } catch (loadError) {
        console.error('Failed to load camera samples.', loadError);
      }
    }

    void loadCameraSamples();
    return () => {
      isActive = false;
    };
  }, []);

  useEffect(() => {
    if (page <= totalPages) {
      return;
    }
    setPage(totalPages);
  }, [page, totalPages]);

  function clearSelection() {
    setSelectedIds(new Set());
    setLastSelectedImageId(null);
  }

  function reloadImages() {
    setReloadKey((current) => current + 1);
  }

  function searchImages() {
    setSearchTerms(parsePromptTerms(searchText));
    setPage(1);
    clearSelection();
  }

  function searchCameraSample(sample: string) {
    setSearchText(sample);
    setSearchTerms([sample]);
    setPage(1);
    clearSelection();
  }

  function changeSort(value: ImageSortValue) {
    setSortValue(value);
    setPage(1);
    clearSelection();
  }

  function changeFamilyMode(value: boolean) {
    setIsFamilyMode(value);
    setPage(1);
    clearSelection();
  }

  function changeSelectionMode(value: boolean) {
    setIsSelectionMode(value);
    if (!value) {
      clearSelection();
    }
  }

  function changePage(nextPage: number) {
    setPage(nextPage);
    clearSelection();
  }

  function toggleImageSelection(imageId: number) {
    setSelectedIds((current) => {
      const next = new Set(current);
      if (next.has(imageId)) {
        next.delete(imageId);
      } else {
        next.add(imageId);
      }
      return next;
    });
    setLastSelectedImageId(imageId);
  }

  function selectImageRange(imageId: number) {
    const pageImageIds = images
      .map(getImageId)
      .filter((id): id is number => id !== null);
    const startIndex = lastSelectedImageId === null ? -1 : pageImageIds.indexOf(lastSelectedImageId);
    const endIndex = pageImageIds.indexOf(imageId);

    if (startIndex === -1 || endIndex === -1) {
      toggleImageSelection(imageId);
      return;
    }

    const minIndex = Math.min(startIndex, endIndex);
    const maxIndex = Math.max(startIndex, endIndex);
    const rangeIds = pageImageIds.slice(minIndex, maxIndex + 1);
    setSelectedIds((current) => {
      const next = new Set(current);
      rangeIds.forEach((rangeId) => next.add(rangeId));
      return next;
    });
    setLastSelectedImageId(imageId);
  }

  function handleTileClick(image: ImageRecord, isRangeSelection: boolean) {
    const imageId = getImageId(image);
    if (imageId === null) {
      return;
    }
    if (!isSelectionMode) {
      setDetailImage(image);
      return;
    }
    if (isRangeSelection) {
      selectImageRange(imageId);
      return;
    }
    toggleImageSelection(imageId);
  }

  async function deleteImages(targetImages: ImageRecord[]) {
    if (!targetImages.length || isDeleting) {
      return;
    }

    const cutLinkedImages = targetImages.filter((image) => (image.cut_count ?? 0) > 0);
    const deletableImages = targetImages.filter((image) => (image.cut_count ?? 0) === 0);
    const ids = deletableImages
      .map(getImageId)
      .filter((id): id is number => id !== null);
    if (!ids.length) {
      window.alert(`Cut이 연결된 Image ${cutLinkedImages.length}개는 삭제하지 않습니다.`);
      return;
    }

    const excludedMessage = cutLinkedImages.length > 0
      ? `\nCut이 연결된 Image ${cutLinkedImages.length}개는 제외됩니다.`
      : '';
    const confirmed = window.confirm(
      `Image ${ids.length}개를 삭제할까요?${excludedMessage}`,
    );
    if (!confirmed) {
      return;
    }

    setIsDeleting(true);
    setError(null);
    try {
      const response = await dbTables.Image.deleteRows(ids);
      const deletedIds = new Set(response.deleted_ids);
      if (detailImage?.id && deletedIds.has(detailImage.id)) {
        setDetailImage(null);
      }
      clearSelection();
      reloadImages();
      if (response.skipped_cut_linked_ids.length > 0) {
        window.alert(
          `Cut이 연결된 Image ${response.skipped_cut_linked_ids.length}개는 삭제하지 않았습니다.`,
        );
      }
    } catch (deleteError) {
      setError(getErrorMessage(deleteError));
    } finally {
      setIsDeleting(false);
    }
  }

  function deleteSelectedImages() {
    const targetImages = images.filter((image) => {
      const imageId = getImageId(image);
      return imageId !== null && selectedIds.has(imageId);
    });
    void deleteImages(targetImages);
  }

  async function loadQuickGenerateDefaults() {
    setIsQuickGenerateLoading(true);
    setQuickGenerateError(null);
    try {
      const defaults = await dbTables.ImageUtil.getImageSettingsDefaults();
      const imageSettings = readSessionImageSettings(defaults);
      if (!isMountedRef.current) {
        return;
      }
      setQuickGenerateSettings(imageSettings);
      setQuickGeneratePositivePrompt(imageSettings.prompt_default_positive);
      setQuickGenerateNegativePrompt(imageSettings.prompt_default_negative);
    } catch (loadError) {
      if (isMountedRef.current) {
        setQuickGenerateError(getErrorMessage(loadError));
      }
    } finally {
      if (isMountedRef.current) {
        setIsQuickGenerateLoading(false);
      }
    }
  }

  function openQuickGenerateModal() {
    if (isQuickGenerateLoading || isQuickGenerateSubmitting) {
      return;
    }
    setIsQuickGenerateOpen(true);
    void loadQuickGenerateDefaults();
  }

  function closeQuickGenerateModal() {
    if (isQuickGenerateLoading || isQuickGenerateSubmitting) {
      return;
    }
    setIsQuickGenerateOpen(false);
    setQuickGenerateError(null);
  }

  async function submitQuickGenerateImage() {
    if (isQuickGenerateLoading || isQuickGenerateSubmitting) {
      return;
    }

    const positivePrompt = quickGeneratePositivePrompt.trim();
    const negativePrompt = quickGenerateNegativePrompt.trim();
    if (!positivePrompt) {
      setQuickGenerateError('positive prompt를 입력해 주세요.');
      return;
    }
    if (!quickGenerateSettings) {
      setQuickGenerateError('이미지 설정을 불러오지 못했습니다.');
      return;
    }

    setIsQuickGenerateSubmitting(true);
    setQuickGenerateError(null);
    try {
      await dbTables.Image.generateImage([
        {
          positive_prompt: positivePrompt,
          negative_prompt: negativePrompt || null,
          model_parameters: quickGenerateSettings,
        },
      ]);
      if (!isMountedRef.current) {
        return;
      }
      setIsQuickGenerateOpen(false);
      setPage(1);
      clearSelection();
      reloadImages();
    } catch (generateError) {
      if (isMountedRef.current) {
        setQuickGenerateError(getErrorMessage(generateError));
      }
    } finally {
      if (isMountedRef.current) {
        setIsQuickGenerateSubmitting(false);
      }
    }
  }

  async function startAutoGenerateImages() {
    if (isAutoGenerating || autoGenerationActiveRef.current) {
      return;
    }

    const runId = autoGenerationRunIdRef.current + 1;
    let generatedCount = 0;
    let hasFailed = false;
    autoGenerationRunIdRef.current = runId;
    autoGenerationStopRef.current = false;
    autoGenerationActiveRef.current = true;
    setIsAutoGenerating(true);
    setIsAutoGenerationStopping(false);
    setAutoGeneratedCount(0);
    setAutoGenerationMessage('자동 생성 준비 중');
    setError(null);

    try {
      const [settingsDefaults, cutResponse] = await Promise.all([
        dbTables.ImageUtil.getImageSettingsDefaults(),
        dbTables.Cut.listRows(AUTO_PROMPT_CUT_LIST_REQUEST),
      ]);
      const imageSettings = readSessionImageSettings(settingsDefaults);
      const cuts = cutResponse.items;
      const autoGenerationBatchSize = Math.max(1, imageSettings.available_gpu_ids.length);

      while (!autoGenerationStopRef.current && autoGenerationRunIdRef.current === runId) {
        const requests: GenerateImageRequest[] = [];
        for (let index = 0; index < autoGenerationBatchSize; index += 1) {
          const { positivePrompt, negativePrompt } = buildAutoGeneratePrompt(imageSettings, cuts);
          if (!positivePrompt) {
            throw new Error('자동 생성 positive prompt를 만들 수 없습니다.');
          }
          requests.push({
            positive_prompt: positivePrompt,
            negative_prompt: negativePrompt,
            model_parameters: imageSettings,
          });
        }

        if (isMountedRef.current && autoGenerationRunIdRef.current === runId) {
          const batchEndCount = generatedCount + requests.length;
          setAutoGenerationMessage(`자동 생성 중 ${generatedCount + 1}-${batchEndCount}`);
        }

        const generatedImages = await dbTables.Image.generateImage(requests);

        generatedCount += generatedImages.length;
        if (isMountedRef.current && autoGenerationRunIdRef.current === runId) {
          setAutoGeneratedCount(generatedCount);
          setAutoGenerationMessage(`자동 생성 ${generatedCount}개 완료`);
          reloadImages();
        }
      }
    } catch (autoGenerateError) {
      hasFailed = true;
      if (isMountedRef.current && autoGenerationRunIdRef.current === runId) {
        setError(getErrorMessage(autoGenerateError));
        setAutoGenerationMessage(`자동 생성 중지됨 · ${generatedCount}개 완료`);
      }
    } finally {
      if (isMountedRef.current && autoGenerationRunIdRef.current === runId) {
        setIsAutoGenerating(false);
        setIsAutoGenerationStopping(false);
        autoGenerationStopRef.current = false;
        autoGenerationActiveRef.current = false;
        if (!hasFailed) {
          setAutoGenerationMessage(generatedCount > 0 ? `자동 생성 ${generatedCount}개 완료` : null);
        }
      }
    }
  }

  function stopAutoGenerateImages() {
    if (!isAutoGenerating && !autoGenerationActiveRef.current) {
      return;
    }
    autoGenerationStopRef.current = true;
    setIsAutoGenerationStopping(true);
    setAutoGenerationMessage('현재 생성 완료 후 정지합니다.');
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-col gap-2 px-1">
        <p className="text-[0.85rem] tracking-[0.16em] text-[var(--app-muted)] uppercase">
          Image archive
        </p>
        <h1 className="text-[clamp(1.25rem,2vw,2.2rem)] leading-[1.05] font-extrabold tracking-[0.02em] text-[#fff7ef] [text-shadow:0_0_22px_rgba(255,194,211,0.42),0_2px_12px_rgba(0,0,0,0.58)]">
          Image 관리
        </h1>
      </div>

      <Panel>
        <PanelHeader className="flex-col items-stretch">
          <ImageManagerToolbar
            searchText={searchText}
            sortValue={sortValue}
            isFamilyMode={isFamilyMode}
            isSelectionMode={isSelectionMode}
            selectedCount={selectedIds.size}
            selectedCutCount={currentSelectedCutCount}
            totalRows={totalRows}
            isLoading={isLoading}
            isDeleting={isDeleting}
            isAutoGenerating={isAutoGenerating}
            isAutoGenerationStopping={isAutoGenerationStopping}
            isQuickGenerating={isQuickGenerateLoading || isQuickGenerateSubmitting}
            autoGeneratedCount={autoGeneratedCount}
            autoGenerationMessage={autoGenerationMessage}
            onSearchTextChange={setSearchText}
            onSearch={searchImages}
            onSortChange={changeSort}
            onFamilyModeChange={changeFamilyMode}
            onSelectionModeChange={changeSelectionMode}
            onDeleteSelected={deleteSelectedImages}
            onOpenQuickGenerate={openQuickGenerateModal}
            onStartAutoGenerate={() => {
              void startAutoGenerateImages();
            }}
            onStopAutoGenerate={stopAutoGenerateImages}
          />
          <CameraSampleChips
            cameraSamples={cameraSamples}
            onSelectSample={searchCameraSample}
          />
        </PanelHeader>

        <SectionBody className="space-y-4">
          <ImageTileGrid
            images={images}
            selectedIds={selectedIds}
            isSelectionMode={isSelectionMode}
            isLoading={isLoading}
            error={error}
            onTileClick={handleTileClick}
          />

          <div className="flex flex-wrap items-center justify-between gap-2 border-t border-[var(--app-border)] pt-4">
            <span className="text-xs font-semibold text-[var(--app-muted)]">
              {page} / {totalPages} · {images.length} / {totalRows}
            </span>
            <div className="flex gap-2">
              <Button
                className="px-4 py-2 text-xs"
                onClick={() => changePage(Math.max(1, page - 1))}
                disabled={page <= 1 || isLoading || isDeleting}
              >
                이전
              </Button>
              <Button
                className="px-4 py-2 text-xs"
                onClick={() => changePage(Math.min(totalPages, page + 1))}
                disabled={page >= totalPages || isLoading || isDeleting}
              >
                다음
              </Button>
            </div>
          </div>
        </SectionBody>
      </Panel>

      {detailImage ? (
        <ImageDetailModal
          image={detailImage}
          isDeleting={isDeleting}
          onClose={() => setDetailImage(null)}
          onDelete={(image) => void deleteImages([image])}
        />
      ) : null}

      {isQuickGenerateOpen ? (
        <ImageQuickGenerateModal
          positivePrompt={quickGeneratePositivePrompt}
          negativePrompt={quickGenerateNegativePrompt}
          isLoadingDefaults={isQuickGenerateLoading}
          isSubmitting={isQuickGenerateSubmitting}
          error={quickGenerateError}
          onPositivePromptChange={setQuickGeneratePositivePrompt}
          onNegativePromptChange={setQuickGenerateNegativePrompt}
          onReloadDefaults={() => {
            void loadQuickGenerateDefaults();
          }}
          onSubmit={() => {
            void submitQuickGenerateImage();
          }}
          onClose={closeQuickGenerateModal}
        />
      ) : null}
    </div>
  );
}
